// <auto-generated />
namespace IdentityMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_all_model_bgst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_all_model_bgst));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021231031_add_all_model_bgst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
